steps:       
  # Build a Docker container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/evp-referral-service:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/evp-referral-service:$COMMIT_SHA']

  - name: 'node:10.15.1'
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - 'FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - 'FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN}'
      - 'FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - 'FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET}'
      - 'FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID}'
      - 'FIREBASE_APP_ID=${_FIREBASE_APP_ID}'
      - 'FIREBASE_MEASUREMENT_ID=${_FIREBASE_MEASUREMENT_ID}'
      - 'FIREBASE_SERVICE_ACCOUNT_PATH=${_FIREBASE_SERVICE_ACCOUNT_PATH}'
      - 'TWITTER_CONSUMER_KEY=${_TWITTER_CONSUMER_KEY}'
      - 'TWITTER_CONSUMER_SECRET=${_TWITTER_CONSUMER_SECRET}'
      - 'TWITTER_CALLBACK_URL=${_TWITTER_CALLBACK_URL}'
      - 'MYSQL_HOST=${_MYSQL_HOST}'
      - 'MYSQL_PORT=${_MYSQL_PORT}'
      - 'MYSQL_USER=${_MYSQL_USER}'
      - 'MYSQL_PASSWORD=${_MYSQL_PASSWORD}'
      - 'MYSQL_DATABASE=${_MYSQL_DATABASE}'
      - 'APP_PORT=${_APP_PORT}'

  # Deploy the container to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'evp-referral-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/evp-referral-service:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--region'
      - 'us-central1'
      - '--port'
      - '8080'
